apiVersion: v1
kind: ConfigMap
metadata:
  name: pr-conf
  namespace: cap
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s 
      evaluation_interval: 15s 
    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]
      - job_name: "exporter"
        static_configs:
          
          - targets: ["mongodb-0.mongodb:27017"]

